# fly.toml app configuration file generated for mywater-payment-svc on 2024-01-30T15:33:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mywater-payment-svc'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
